#!/usr/bin/env python3
"""Audit nested rapidity-node and zero-field limits of adaptive GHD runs.

The script accepts trajectory-free certificates generated by
``derive_regulated_infinite_mode_fghd.py``.  All inputs must have identical
regulators apart from the magnetic field and the number of adaptive nodes per
string.  It first extrapolates each field in ``N_node^{-p}``, then performs the
small-field fits.  A subleading coefficient is deliberately ineligible unless
the nested sequence reproduces the exact leading coefficient.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.heisenberg_burgers_bridge import EXACT_D0_INFINITY_T  # noqa: E402


_REGULATOR_KEYS = (
    "string_xi_cutoff",
    "string_xi_buffer",
    "scaled_rapidity_extent",
    "scaled_rapidity_map_alpha",
    "kernel_theta_step",
    "rapidity_quadrature",
    "operator_only",
)


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("certificates", type=Path, nargs="+")
    parser.add_argument("--node-powers", type=float, nargs="+", default=[2, 3, 4])
    parser.add_argument("--minimum-nodes-per-field", type=int, default=3)
    parser.add_argument("--minimum-susceptibility-capture", type=float, default=0.985)
    parser.add_argument("--maximum-leading-relative-error", type=float, default=0.01)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def _regulator_signature(payload: dict) -> dict:
    regulators = payload["regulators"]
    return {key: regulators.get(key) for key in _REGULATOR_KEYS}


def _linear_intercept(x: np.ndarray, y: np.ndarray) -> tuple[float, float]:
    coefficient = np.polyfit(x, y, 1)
    residual = y - np.polyval(coefficient, x)
    return float(coefficient[1]), float(np.sqrt(np.mean(residual**2)))


def main() -> int:
    args = _arguments()
    if len(args.node_powers) < 2 or any(power <= 0 for power in args.node_powers):
        raise ValueError("provide at least two positive node-extrapolation powers")

    rows: list[dict] = []
    signature = None
    for path in args.certificates:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if payload.get("uses_target_a_or_D") or payload.get("uses_target_trajectory"):
            raise RuntimeError(f"target-contaminated certificate: {path}")
        current = _regulator_signature(payload)
        if signature is None:
            signature = current
        elif current != signature:
            raise RuntimeError(
                "incompatible regulator signatures: "
                f"expected {signature}, found {current} in {path}"
            )
        nodes = int(payload["regulators"]["nodes_per_string"])
        for row in payload["rows"]:
            rows.append(
                {
                    "source": str(path),
                    "field": float(row["field"]),
                    "nodes_per_string": nodes,
                    "h_times_spin_diffusion": float(row["h_times_spin_diffusion"]),
                    "susceptibility_captured_fraction": float(
                        row["susceptibility_captured_fraction"]
                    ),
                    "fdt_residual": float(row["fdt_residual"]),
                }
            )

    grouped: dict[float, list[dict]] = {}
    for row in rows:
        grouped.setdefault(row["field"], []).append(row)
    if len(grouped) < 4:
        raise ValueError("need at least four fields for a zero-field audit")

    node_limits: list[dict] = []
    for field in sorted(grouped):
        group = sorted(grouped[field], key=lambda item: item["nodes_per_string"])
        if len(group) < args.minimum_nodes_per_field:
            raise ValueError(
                f"field {field} has {len(group)} node counts; "
                f"need {args.minimum_nodes_per_field}"
            )
        nodes = np.asarray([row["nodes_per_string"] for row in group], dtype=float)
        values = np.asarray([row["h_times_spin_diffusion"] for row in group])
        schemes = []
        for power in args.node_powers:
            intercept, rms = _linear_intercept(nodes ** (-power), values)
            schemes.append(
                {
                    "power": float(power),
                    "zero_node_spacing_limit": intercept,
                    "rms_residual": rms,
                }
            )
        limits = np.asarray([item["zero_node_spacing_limit"] for item in schemes])
        node_limits.append(
            {
                "field": field,
                "input_rows": group,
                "schemes": schemes,
                "limit_envelope": {
                    "minimum": float(np.min(limits)),
                    "maximum": float(np.max(limits)),
                    "center": float(0.5 * (np.min(limits) + np.max(limits))),
                    "half_width": float(0.5 * (np.max(limits) - np.min(limits))),
                },
            }
        )

    fields = np.asarray([item["field"] for item in node_limits])
    field_fits = []
    fixed_d0_fits = []
    for scheme_index, power in enumerate(args.node_powers):
        values = np.asarray(
            [item["schemes"][scheme_index]["zero_node_spacing_limit"] for item in node_limits]
        )
        for degree in (1, 2):
            coefficient = np.polyfit(fields, values, degree)
            residual = values - np.polyval(coefficient, fields)
            field_fits.append(
                {
                    "node_power": float(power),
                    "field_model": f"polynomial_degree_{degree}",
                    "coefficients_descending": coefficient.tolist(),
                    "zero_field_intercept": float(coefficient[-1]),
                    "rms_residual": float(np.sqrt(np.mean(residual**2))),
                }
            )
        linear_d1 = float(
            np.dot(fields, values - EXACT_D0_INFINITY_T) / np.dot(fields, fields)
        )
        design = np.column_stack((fields, fields**2))
        d1, d2 = np.linalg.lstsq(
            design, values - EXACT_D0_INFINITY_T, rcond=None
        )[0]
        fixed_d0_fits.append(
            {
                "node_power": float(power),
                "fixed_exact_D0_linear_D1": linear_d1,
                "fixed_exact_D0_quadratic_D1": float(d1),
                "fixed_exact_D0_quadratic_D2": float(d2),
            }
        )

    intercepts = np.asarray([fit["zero_field_intercept"] for fit in field_fits])
    leading_relative_errors = np.abs(intercepts / EXACT_D0_INFINITY_T - 1.0)
    capture_pass = all(
        row["susceptibility_captured_fraction"]
        >= args.minimum_susceptibility_capture
        for row in rows
    )
    leading_pass = bool(
        capture_pass
        and np.max(leading_relative_errors) <= args.maximum_leading_relative_error
    )
    d1_values = np.asarray(
        [
            fit["fixed_exact_D0_linear_D1"]
            for fit in fixed_d0_fits
        ]
        + [
            fit["fixed_exact_D0_quadratic_D1"]
            for fit in fixed_d0_fits
        ]
    )
    result = {
        "schema": 1,
        "method": "nested_adaptive_node_then_zero_field_limit",
        "uses_target_trajectory": False,
        "uses_target_a_or_D": False,
        "regulator_signature": signature,
        "exact_D0": float(EXACT_D0_INFINITY_T),
        "node_limits": node_limits,
        "field_fits": field_fits,
        "fixed_exact_D0_diagnostic_fits": fixed_d0_fits,
        "diagnostic_D1_envelope": {
            "minimum": float(np.min(d1_values)),
            "maximum": float(np.max(d1_values)),
            "eligible_as_physical_interval": leading_pass,
        },
        "gates": {
            "minimum_susceptibility_capture": args.minimum_susceptibility_capture,
            "susceptibility_capture_pass": capture_pass,
            "maximum_leading_relative_error": args.maximum_leading_relative_error,
            "maximum_observed_leading_relative_error": float(
                np.max(leading_relative_errors)
            ),
            "leading_D0_gate_pass": leading_pass,
            "physical_D1_certified": False,
            "physical_D1_reason": (
                "leading D0 gate failed; subtracting D0/h would amplify the "
                "unresolved joint regulator error"
                if not leading_pass
                else "leading gate passed, but independent xi/R/kernel and smaller-field "
                "stability gates are not supplied by this certificate"
            ),
        },
    }
    encoded = json.dumps(result, indent=2, sort_keys=True) + "\n"
    print(encoded, end="")
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(encoded, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
