#!/usr/bin/env python3
"""Generate all numerical TeX macros and the protection-class table for Paper II."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path
from typing import Any

import numpy as np


SCRIPT_ROOT = Path(__file__).resolve().parent
DEFAULT_REPO = SCRIPT_ROOT.parents[2]
THEORY_OUTPUT = SCRIPT_ROOT / "output/geometric_eth_theory_v14"
DEFAULT_RESULTS = DEFAULT_REPO / "overleaf_sync/geometric_eth_theory/generated/results_v14.tex"
DEFAULT_CLASSES = DEFAULT_REPO / "overleaf_sync/geometric_eth_theory/generated/protection_classes_v14.tex"


def _load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise RuntimeError(f"input is not a JSON object: {path}")
    return value


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
            os.fchmod(handle.fileno(), 0o644)
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def _fmt(value: float, digits: int = 5) -> str:
    return f"{float(value):.{digits}f}"


def build_inputs(
    repo_root: Path,
    *,
    results_path: Path,
    classes_path: Path,
) -> dict[str, Any]:
    root = Path(repo_root)
    output = root / "01_task_folder/task_05/script/output/geometric_eth_theory_v14"
    channel = _load(output / "channel_theory_v14.json")
    prediction = _load(output / "chiral_prediction_v14.json")
    outcomes = _load(output / "chiral_outcomes_v14.json")
    inference = _load(output / "chiral_inference_v14.json")
    archival = _load(output / "effective_channel_inference_v14.json")
    gate = _load(output / "theory_gate_v14.json")

    random_cases = inference["class_inference"]["random"]["cases"]
    local_cases = inference["class_inference"]["local"]["cases"]
    structured_cases = inference["class_inference"]["structured"]["cases"]
    safe_records = [
        safe
        for case in outcomes["cases"].values()
        for record in case["classes"].values()
        for safe in record["safe_covariates"]
    ]
    gaps = np.asarray([safe["external_gap"] for safe in safe_records], dtype=float)
    finite_differences = np.asarray(
        [safe["projector_finite_difference_relative"] for safe in safe_records],
        dtype=float,
    )
    gauge_errors = np.asarray(
        [safe["gauge_response_relative"] for safe in safe_records], dtype=float
    )
    whitening_errors = np.asarray(
        [safe["channel_whitening"]["identity_error"] for safe in safe_records],
        dtype=float,
    )

    selected_title = gate["selected_title"]
    lines = [
        "% Generated by make_geometric_eth_theory_inputs_v14.py; do not edit by hand.",
        f"% channel_theory_sha256={_sha256(output / 'channel_theory_v14.json')}",
        f"% chiral_prediction_sha256={_sha256(output / 'chiral_prediction_v14.json')}",
        f"% chiral_outcomes_sha256={_sha256(output / 'chiral_outcomes_v14.json')}",
        f"% chiral_inference_sha256={_sha256(output / 'chiral_inference_v14.json')}",
        _macro("PaperIITitle", selected_title),
        _macro("PaperIIGatePassed", "true" if gate["passed"] else "false"),
        _macro("PaperIIBranch", r"\texttt{random\_channel\_failure}"),
        _macro("ChannelTheoryMaximumRelativeError", _fmt(channel["maximum_relative_error"], 5)),
        _macro("ChannelTheoryRegisteredCounts", "4, 8, 16, 32, 64"),
        _macro("ChiralDevelopmentSizes", "$(16,24)$, $(24,36)$, and $(32,48)$"),
        _macro("ChiralValidationSizes", "$(48,72)$, $(64,96)$, and $(96,144)$"),
        _macro("ChiralBasesPerSize", str(prediction["registered_grid"]["bases_per_size"])),
        _macro("ChiralTangentsPerBase", str(prediction["registered_grid"]["tangents_per_base"])),
        _macro("ChiralBandLower", _fmt(inference["random_primary"]["band"]["lower"])),
        _macro("ChiralBandUpper", _fmt(inference["random_primary"]["band"]["upper"])),
        _macro("ChiralSafeBaseCount", str(len(safe_records))),
        _macro("ChiralGapMinimum", _fmt(float(np.min(gaps)), 4)),
        _macro("ChiralGapMaximum", _fmt(float(np.max(gaps)), 4)),
        _macro("ChiralMaximumFiniteDifferenceError", f"{float(np.max(finite_differences)):.2e}"),
        _macro("ChiralMaximumGaugeError", f"{float(np.max(gauge_errors)):.2e}"),
        _macro("ChiralMaximumWhiteningError", f"{float(np.max(whitening_errors)):.2e}"),
        _macro("PaperIIMappedArchivalCases", str(len(archival["mapped_cases"]))),
        _macro("PaperIIExcludedArchivalModels", str(len(archival["excluded_models"]))),
    ]
    labels = ("One", "Two", "Three")
    for label, case in zip(labels, random_cases, strict=True):
        lines.extend(
            [
                _macro(f"ChiralRandom{label}Point", _fmt(case["point_estimate"])),
                _macro(f"ChiralRandom{label}Low", _fmt(case["interval_low"])),
                _macro(f"ChiralRandom{label}High", _fmt(case["interval_high"])),
            ]
        )
    for prefix, cases in (("Local", local_cases), ("Structured", structured_cases)):
        for label, case in zip(labels, cases, strict=True):
            lines.extend(
                [
                    _macro(f"Chiral{prefix}{label}Point", _fmt(case["point_estimate"])),
                    _macro(f"Chiral{prefix}{label}Low", _fmt(case["interval_low"])),
                    _macro(f"Chiral{prefix}{label}High", _fmt(case["interval_high"])),
                ]
            )
    _atomic_text(results_path, "\n".join(lines) + "\n")

    table = r"""% Generated protection classes; mechanism constrains kinematics but does not determine statistics.
\begingroup
\footnotesize
\setlength{\tabcolsep}{3pt}
\newcommand{\pcell}[2]{\parbox[t]{#1}{\raggedright #2\strut}}
\begin{tabular}{@{}lllll@{}}
\toprule
\pcell{1.05in}{\textbf{Protection class}} & \pcell{1.38in}{\textbf{Exact degeneracy}} & \pcell{1.30in}{\textbf{Motion of $P$}} & \pcell{1.45in}{\textbf{Response-algebra obstruction}} & \pcell{1.37in}{\textbf{How exactness is lost}} \\
\midrule
\pcell{1.05in}{Common kernel / parent} & \pcell{1.38in}{Positive constraints share a null space; quasihole or clustering rules fix $D$.} & \pcell{1.30in}{Constraint tensors or boundary twists move the common kernel.} & \pcell{1.45in}{Tangent choice may be central, reducible, or full; the parent form does not determine statistics.} & \pcell{1.37in}{A generic term not annihilating the kernel, Landau-level mixing, or a gap closing.} \\
\pcell{1.05in}{Cohomological} & \pcell{1.38in}{$H=\{Q,Q^\dagger\}$ and $Q^2=0$ identify zero modes with cohomology.} & \pcell{1.30in}{Deformations of $Q$ move exact and coexact complements.} & \pcell{1.45in}{Hodge blocks can leave a nonscalar commutant even when curvature is nonzero.} & \pcell{1.37in}{Breaking nilpotency or supersymmetry, or changing cohomology across a singular point.} \\
\pcell{1.05in}{Stabilizer} & \pcell{1.38in}{Mutually commuting projectors and logical operators fix an exact code space.} & \pcell{1.30in}{Coefficient changes leave $P$ fixed; conjugations can move it isospectrally.} & \pcell{1.45in}{Frozen or scalar response is common at solvable points.} & \pcell{1.37in}{Noncommuting perturbations, boundaries, or virtual logical processes at finite size.} \\
\pcell{1.05in}{Chiral / index} & \pcell{1.38in}{Full-row-rank $T\in\mathbb C^{n_b\times n_a}$ gives $D=n_a-n_b$.} & \pcell{1.30in}{Rectangular-factor tangents move $\ker T$ while the index stays fixed.} & \pcell{1.45in}{Random tangents need not close under $N_{\rm eff}$ alone, as the sealed test shows.} & \pcell{1.37in}{Rank loss, a closing singular-value gap, or chiral-symmetry breaking.} \\
\pcell{1.05in}{Symmetry multiplet} & \pcell{1.38in}{An irreducible representation, Kramers theorem, or conserved charge fixes a multiplet.} & \pcell{1.30in}{Symmetry-preserving couplings rotate the representation bundle.} & \pcell{1.45in}{The commutant contains unresolved symmetry blocks until sectors are resolved.} & \pcell{1.37in}{A field or perturbation that breaks the protecting symmetry.} \\
\pcell{1.05in}{Integrable / spectrum-generating algebra} & \pcell{1.38in}{Hidden commuting charges or a spectrum-generating algebra enforce multiplets.} & \pcell{1.30in}{Algebra-preserving parameter changes transport the representation.} & \pcell{1.45in}{A large commutant is expected and obstructs unrestricted mixing.} & \pcell{1.37in}{Generic charge-breaking terms, truncation of long-range couplings, or disorder.} \\
\bottomrule
\end{tabular}
\endgroup
"""
    _atomic_text(classes_path, table)
    return {
        "gate_passed": bool(gate["passed"]),
        "selected_branch": inference["selected_branch"],
        "selected_title": selected_title,
        "result_macro_count": sum(line.startswith("\\newcommand") for line in lines),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=DEFAULT_REPO)
    parser.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    parser.add_argument("--classes", type=Path, default=DEFAULT_CLASSES)
    arguments = parser.parse_args()
    payload = build_inputs(
        arguments.repo_root,
        results_path=arguments.results,
        classes_path=arguments.classes,
    )
    print(json.dumps(payload, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
